### ISSUE TITLE
题目太长的问题

### ISSUE THREAD

**Issue by wlufy** [ZhouKanglei/BUAAProposal#1]
题目太长，封面页放不下怎么办

**Comment by ZhouKanglei** [comment]
已更新 cls 文件，支持题目自动换行：

`\begin{tabular}{lp{8cm}<{\centering}} % 8cm是单元格宽度，如果希望换行垂直居中则改为lm{8cm}<{\centering}`

**Comment by wlufy** [comment]
已解决，感谢！
